repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: >-
            (?x)^(
                tests/.*.*out|
                tests/.*.in$
            )$

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.55'
    hooks:
    -   id: flynt
        args: [
            '--line-length=120',
            '--fail-on-change',
        ]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

## Seems to be conflicting with one of the previous pre-commits (e.g. on the number of empty
## lines after a class docstring)
#-   repo: https://github.com/PyCQA/pydocstyle
#    rev: 5.0.2
#    hooks:
#    -   id: pydocstyle
#        # NOTE THIS MIGHT NEED TO BE MOVED LATER, OR SWAP THE DEFINITION AND THE USE OF EXCLUDE IF YOU UNCOMMENT
#        exclude: *exclude_files
#        args: ['--ignore=D104,D202,D203,D213,D401']

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        args: ['-i']
        exclude: 'docs/source/conf.py'

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        language: system
        exclude: &exclude_files >
            (?x)^(
                docs/.*|
                tests/.*(?<!\.py)$
            )$
