repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: >-
            (?x)^(
                tests/.*.*out|
                tests/.*.in$
            )$

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.55'
    hooks:
    -   id: flynt
        args: [
            '--line-length=120',
            '--fail-on-change',
        ]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.262'
    hooks:
        - id: ruff
