name: cd

on:
    push:
        tags:
        -   'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

    validate-release-tag:

        if: github.repository == 'aiidateam/aiida-submission-controller'
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout source
            uses: actions/checkout@v2

        -   name: Set up Python 3.11
            uses: actions/setup-python@v2
            with:
                python-version: '3.11'

        -   name: Validate the tag version against the package version
            run: python .github/workflows/validate_release_tag.py $GITHUB_REF

    publish:

        name: Publish to PyPI
        needs: [validate-release-tag]
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout source
            uses: actions/checkout@v3

        -   name: Set up Python 3.11
            uses: actions/setup-python@v4
            with:
                python-version: '3.11'

        -   name: Install flit
            run: pip install --upgrade flit

        -   name: Build and publish
            run: flit publish
            env:
                FLIT_USERNAME: __token__
                FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
